apiVersion: v1
kind: Service
metadata:
  name: {{ include "acm-sync.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "acm-sync.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "acm-sync.selectorLabels" . | nindent 4 }}
