name: E2E Tests

on:
  push:
  pull_request:

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
        env:
          SERVICES: acm
          DEFAULT_REGION: us-east-1
        options: >-
          --health-cmd "curl -f http://localhost:4566/_localstack/health || exit 1"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Wait for LocalStack
        run: curl --retry 10 --retry-delay 2 --retry-connrefused http://localhost:4566/_localstack/health

      - name: Run LocalStack e2e tests
        run: go test -tags=e2e -v -count=1 ./test/e2e/ -run LocalStack
