name: E2E Tests

on:
  pull_request:
    branches: [main]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    services:
      moto:
        image: motoserver/moto:latest
        ports:
          - 5000:5000
        env:
          MOTO_SERVICE: acm
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Wait for moto
        run: curl --retry 10 --retry-delay 2 --retry-connrefused http://localhost:5000/moto-api/

      - name: Run e2e tests
        env:
          ACM_ENDPOINT: http://localhost:5000
        run: go test -tags=e2e -v -count=1 ./test/e2e/acm/
